name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install dependencies
        run: pnpm build

      - name: Add other env secrets
        run: |
          echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> .env 

      - name: Add other env secrets
        run: |
          echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> .env && \
            echo "CI='true'" >> .env && \
            echo "RPC_API_KEY=${{ secrets.RPC_API_KEY }}" >> .env && \
            echo "RPC_BASE_URL=${{ secrets.RPC_BASE_URL }}" >> .env && \
            echo "PRIVATE_KEY_BASE_WALLET=${{ secrets.PRIVATE_KEY_BASE_WALLET }}" >> .env

      - name: Run e2e tests
        run: pnpm test:e2e
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          CI: true
          RPC_API_KEY: ${{ secrets.RPC_API_KEY }}
          RPC_BASE_URL: ${{ secrets.RPC_BASE_URL }}
          PRIVATE_KEY_BASE_WALLET: ${{ secrets.PRIVATE_KEY_BASE_WALLET }}

